In [1]:
import pandas as pd
import re
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
df=pd.read_csv("cleaned_Review_dataset.csv")
df.head()

,review_id,product_id,rating,review_time,summary,review_text,review_date,sentiment
0,1,B001E4KFG0,5,1303862400,Good Quality Dog Food,I have bought several of the Vitality canned d...,2011-04-27,Positive
1,2,B00813GRG4,1,1346976000,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...,2012-09-07,Negative
2,3,B000LQOCH0,4,1219017600,"""Delight"" says it all",This is a confection that has been around a fe...,2008-08-18,Positive
3,4,B000UA0QIQ,2,1307923200,Cough Medicine,If you are looking for the secret ingredient i...,2011-06-13,Negative
4,5,B006K2ZZ7K,5,1350777600,Great taffy,Great taffy at a great price. There was a wid...,2012-10-21,Positive

In [3]:
#Text cleaning function
def clean_text(text):
    text = str(text).lower()              #str(text) → text ko string banata hai, lower() → capital letters ko small karta hai
    text = re.sub(r'[^a-z\s]', '', text)  #re.sub(r'[^a-z\s]', '', text) → special characters/numbers remove karta hai
    text = re.sub(r'\s+', ' ', text)      #re.sub(r'\s+', ' ', text) → extra spaces remove karta hai
    text = text.strip()                  #strip() → starting/ending spaces remove karta hai
    return text                          #return text → cleaned text return karta hai

In [4]:
#Create Clean review column  :   Har review par cleaning function apply hota hai.
df['clean_review'] = df['review_text'].apply(clean_text)

In [5]:
#Remove Neutrals
df = df[df['sentiment'] != 'Neutral']

In [7]:
#Take Sample data :  WHY?: Full dataset heavy hai. 20,000 rows project ke liye enough hain.
df = df.sample(20000, random_state=42)

In [8]:
df.head()

,review_id,product_id,rating,review_time,summary,review_text,review_date,sentiment,clean_review
443593,443594,B000W5QT3A,5,1309132800,Outstanding Food!!!,This is a very high quality dog food with meat...,2011-06-27,Positive,this is a very high quality dog food with meat...
136949,136950,B002AQP5FW,5,1246579200,Thank you Betty Crocker,I love this cake mix and the other 3 mixes as ...,2009-07-03,Positive,i love this cake mix and the other mixes as we...
520459,520460,B007TJGZ18,4,1322438400,Double Black Diamond,A nice strong brew. I am new to Keurig and hav...,2011-11-28,Positive,a nice strong brew i am new to keurig and have...
219515,219516,B0043WOANY,5,1348012800,Fantastic!,I just found PB2 and PB2 with chocolate and I ...,2012-09-19,Positive,i just found pb and pb with chocolate and i am...
471273,471274,B000E8UAEO,5,1322179200,Revolution tea is fantastic (for bagged tea),Delightful mint tea as one would expect. Note ...,2011-11-25,Positive,delightful mint tea as one would expect note t...

In [10]:
df.shape

(20000, 9)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20000 entries, 443593 to 330800
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   review_id     20000 non-null  int64
 1   product_id    20000 non-null  object
 2   rating        20000 non-null  int64
 3   review_time   20000 non-null  int64
 4   summary       20000 non-null  object
 5   review_text   20000 non-null  object
 6   review_date   20000 non-null  object
 7   sentiment     20000 non-null  object
 8   clean_review  20000 non-null  object
dtypes: int64(3), object(6)
memory usage: 1.5+ MB

In [16]:
df.to_csv("Final_feedback_Revidataset.csv", index=False)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3341829359.py, line 1)